-- Active: 1766742740957@@ep-late-meadow-a1mou9r2-pooler.ap-southeast-1.aws.neon.tech@5432@neondb@public
CREATE TABLE dorm_applications (
    id UUID PRIMARY KEY,
    student_id VARCHAR(32) NOT NULL,
    full_name VARCHAR(128) NOT NULL,
    dob DATE,
    gender VARCHAR(16),
    cccd VARCHAR(32),
    cccd_issue_date DATE,
    cccd_issue_place VARCHAR(128),
    phone VARCHAR(32),
    email VARCHAR(128),
    avatar_front VARCHAR(255),
    avatar_back VARCHAR(255),
    class VARCHAR(32),
    course VARCHAR(32),
    faculty VARCHAR(64),
    ethnicity VARCHAR(32),
    religion VARCHAR(32),
    hometown VARCHAR(128),
    guardian_name VARCHAR(128),
    guardian_phone VARCHAR(32),
    priority_proof VARCHAR(255),
    preferred_site VARCHAR(64),
    preferred_dorm VARCHAR(32),
    priority_group VARCHAR(64),
    admission_type VARCHAR(32),
    status VARCHAR(16) DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_dorm_applications_student_id ON dorm_applications(student_id);